### ISSUE TITLE
Multisite "Cheatin’ uh" Message on EditGames route

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/ivanhoe#195]
#@$%$!#@!$ seriously

On a multisite installation of the theme, the "Games" navigation element is not added to the admin navigation. If you attempt to manually reach the edit view (`/wp-admin/edit.php?post_type=ivanhoe_game`) you get an awesome error message:

![screen shot 2014-09-02 at 9 09 23 am](https://cloud.githubusercontent.com/assets/45000/4118539/6d91b0fe-32a2-11e4-87e0-4dc6bd8f5dd6.png)

**Comment by clioweb** [comment]
See my referenced commit. We used the `update_core` capability to restrict CRUD on games to administrators, but that capability is only available to "super" administrators in multisite. Updated to use a capability that all administrators, on single and multisite WP, have.
