### ISSUE TITLE
Development Environment Setup

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/ivanhoe#215]
We need to have some instructions for contributors to set up their machines, including dependencies for:

* PHP
* MySQL
* Apache (nginx, whatever)
* Ruby
* Qt

This should include a section on how to run the tests and what to expect (e.g. where do the screenshots go).

**Comment by waynegraham** [comment]
Add in info on how to handle branches and merges.

**Comment by swatichawla** [comment]
Dealt with in "how to contribute" section.
