### ISSUE TITLE
Bulk delete games

### ISSUE THREAD

**Issue by clioweb** [scholarslab/ivanhoe#227]
For some reason, the dropdown option to bulk delete games in the admin panel doesn't appear, which means that you have to delete one game at a time to clear them out or remove multiple games.

On this page, I see a notice as well, which is likely related.

```
Notice: Undefined property: stdClass::$delete_posts in /Users/jeremy/Sites/ivanhoe/wp-admin/includes/class-wp-posts-list-table.php on line 250
```

**Comment by csbailey5t** [comment]
Looks like this is this issue in WP that is up for patching shortly:

https://core.trac.wordpress.org/ticket/30991

In the meantime, we can directly address the capability issue.

**Comment by clioweb** [comment]
done.
