### ISSUE TITLE
sidebar styling

### ISSUE THREAD

**Issue by arboyd** [scholarslab/ivanhoe#239]
the text in the sidebar needs to be styled (mostly spacing related) and I am out of steam

**Comment by af3pj** [comment]
Will look at in the Lab AM.

**Comment by jng3au** [comment]
change ordering of character and image

**Comment by jng3au** [comment]
possibly standardize image size.

**Comment by clioweb** [comment]
> possibly standardize image size.

WordPress generates derivative images on upload. We can use those, either the smaller images or the cropped square thumbnail.
