### ISSUE TITLE
Wrong placeholder text on make a game form 

### ISSUE THREAD

**Issue by clioweb** [scholarslab/ivanhoe#240]
The placeholder text on the title for making a game reads like its for a move.

**Comment by csbailey5t** [comment]
This is a result of #214 

Placeholders were added only in BasePostForm and using move specific text to determine whether it was worthwhile moving forward with them, and merged into develop, on my understanding, for screenshot purposes for documentation/presentation.

**Comment by csbailey5t** [comment]
Placeholders have been removed from develop until the feature is finished and post type specific placeholders are scaffolded should the group choose to move forward with them.
