### ISSUE TITLE
Profile page borked

### ISSUE THREAD

**Issue by clioweb** [scholarslab/ivanhoe#248]
Something's amiss.

**Comment by csbailey5t** [comment]
Content is shifted back into the main page in 6b476f7b02fb875360419d6d8a846c83c790e4e8. This leaves the sidebar completely blank on the profile page. Should the sidebar be completely removed? If so, this means taking it out of the header.php and putting it only in templates that require it.

**Comment by arboyd** [comment]
sidebar is still empty (open to suggestions, but idk what should/could go there) but otherwise this is taken care of. adding mention of empty sidebar to #258
